In [26]:
import numpy as np
import pandas as pd
import sqlite3

from sklearn.preprocessing import OneHotEncoder

DATA_PATH = 'MFOcredit.csv'

In [27]:
dft = pd.read_csv(DATA_PATH, encoding='cp1251', sep=';')

In [28]:
con = sqlite3.connect('MFOcredit') #соединяемся с виртуальной базой db

In [29]:
dft.to_sql('MFOcredit', con, index=False, if_exists='replace')


35212

In [30]:
def select(sql):
  return pd.read_sql(sql, con)

In [31]:
sql = '''SELECT * FROM MFOcredit'''

In [32]:
df = select(sql)

In [33]:
df.head(5)

id   date_start     date_end   gender  age          auto  \
0   1  03-Jan-2013  12-Jan-2013  Мужской   44           Нет   
1   2  03-Jan-2013  17-Jan-2013  Мужской   21  Пропуск поля   
2   3  03-Jan-2013  17-Jan-2013  Мужской   25  Пропуск поля   
3   4  03-Jan-2013  17-Jan-2013  Женский   47  Пропуск поля   
4   5  03-Jan-2013  17-Jan-2013  Мужской   22           Нет   

              housing                       marstatus regclient      jobtype  \
0         Собственное  Гражданский брак/женат/замужем       Нет  Официальное   
1  Живут с родителями                          Холост       Нет  Официальное   
2         Собственное                          Холост        Да  Официальное   
3         Собственное  Гражданский брак/женат/замужем        Да  Официальное   
4          Арендуемое  Гражданский брак/женат/замужем       Нет  Официальное   

                      region       credits children delinq60plus  
0      Новосибирская область           Нет       Да          Нет  
1     Кемеровская область юг            Да      Нет          Нет  
2  Кемеровская область север  Пропуск поля      Нет          Нет  
3  Кемеровская область север           Нет      Нет          Нет  
4  Кемеровская область север            Да       Да          Нет

In [34]:
df.shape

(35212, 14)

In [35]:
df.info()
# отстутствуют нулевые значения
# 11 объектов, которые необходимо обработать

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35212 entries, 0 to 35211
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   id            35212 non-null  int64 
 1   date_start    35212 non-null  object
 2   date_end      35212 non-null  object
 3   gender        35212 non-null  object
 4   age           35212 non-null  int64 
 5   auto          35212 non-null  object
 6   housing       35212 non-null  object
 7   marstatus     35212 non-null  object
 8   regclient     35212 non-null  object
 9   jobtype       35212 non-null  object
 10  region        35212 non-null  object
 11  credits       35212 non-null  object
 12  children      35212 non-null  object
 13  delinq60plus  35212 non-null  object
dtypes: int64(2), object(12)
memory usage: 3.8+ MB


In [10]:
df['regclient'].value_counts()

Да     19733
Нет    15479
Name: regclient, dtype: int64

In [11]:
df['jobtype'].value_counts()

Официальное      19588
Пропуск поля     14457
Неофициальное     1167
Name: jobtype, dtype: int64

In [12]:
df['credits'].value_counts()

Нет             18126
Да              16140
Пропуск поля      946
Name: credits, dtype: int64

In [13]:
df['delinq60plus'].value_counts()

Нет    21705
Да     13507
Name: delinq60plus, dtype: int64

In [14]:
df['auto'].value_counts()

Нет             17465
Пропуск поля    14077
Да               3670
Name: auto, dtype: int64

In [15]:
df['marstatus'].value_counts()

Гражданский брак/женат/замужем    14099
Холост                             8833
Пропуск поля                       7564
Разведен                           2871
Вдова/вдовец                       1845
Name: marstatus, dtype: int64

In [16]:
df['housing'].value_counts()

Собственное              18099
Пропуск поля              7603
Живут с родителями        3177
Долевая собственность     2955
Арендуемое                2020
Муниципальное             1358
Name: housing, dtype: int64

In [17]:
df['children'].value_counts()

Нет             21141
Да              13326
Пропуск поля      745
Name: children, dtype: int64

In [36]:
df['delinq60plus'] = df['delinq60plus'].map({'Да': 1, 'Нет': 0})
df['regclient'] = df['regclient'].map({'Да': 1, 'Нет': 0})
df['gender'] = df['gender'].map({'Мужской': 1, 'Женский': 0})

In [37]:
df.head()

id   date_start     date_end  gender  age          auto  \
0   1  03-Jan-2013  12-Jan-2013       1   44           Нет   
1   2  03-Jan-2013  17-Jan-2013       1   21  Пропуск поля   
2   3  03-Jan-2013  17-Jan-2013       1   25  Пропуск поля   
3   4  03-Jan-2013  17-Jan-2013       0   47  Пропуск поля   
4   5  03-Jan-2013  17-Jan-2013       1   22           Нет   

              housing                       marstatus  regclient      jobtype  \
0         Собственное  Гражданский брак/женат/замужем          0  Официальное   
1  Живут с родителями                          Холост          0  Официальное   
2         Собственное                          Холост          1  Официальное   
3         Собственное  Гражданский брак/женат/замужем          1  Официальное   
4          Арендуемое  Гражданский брак/женат/замужем          0  Официальное   

                      region       credits children  delinq60plus  
0      Новосибирская область           Нет       Да             0  
1     Кемеровская область юг            Да      Нет             0  
2  Кемеровская область север  Пропуск поля      Нет             0  
3  Кемеровская область север           Нет      Нет             0  
4  Кемеровская область север            Да       Да             0

In [38]:
#разобъём дату на отдельные данные (года, месяца, дни, кварталы)
date_start = pd.to_datetime(df['date_start'])
date_end = pd.to_datetime(df['date_end'])

df.insert(0, 'start_year', date_start.dt.year)
df.insert(1, 'start_quart', date_start.dt.quarter)
df.insert(2, 'start_month', date_start.dt.month)
df.insert(3, 'start_day', date_start.dt.day)

df.insert(4, 'end_year', date_end.dt.year)
df.insert(5, 'end_quart', date_end.dt.quarter)
df.insert(6, 'end_month', date_end.dt.month)
df.insert(7, 'end_day', date_end.dt.day)

# добавим продолжительность
df.insert(8, 'loang_term', (date_end-date_start).dt.days)


In [39]:
df.head()

start_year  start_quart  start_month  start_day  end_year  end_quart  \
0        2013            1            1          3      2013          1   
1        2013            1            1          3      2013          1   
2        2013            1            1          3      2013          1   
3        2013            1            1          3      2013          1   
4        2013            1            1          3      2013          1   

   end_month  end_day  loang_term  id  ... age          auto  \
0          1       12           9   1  ...  44           Нет   
1          1       17          14   2  ...  21  Пропуск поля   
2          1       17          14   3  ...  25  Пропуск поля   
3          1       17          14   4  ...  47  Пропуск поля   
4          1       17          14   5  ...  22           Нет   

              housing                       marstatus regclient      jobtype  \
0         Собственное  Гражданский брак/женат/замужем         0  Официальное   
1  Живут с родителями                          Холост         0  Официальное   
2         Собственное                          Холост         1  Официальное   
3         Собственное  Гражданский брак/женат/замужем         1  Официальное   
4          Арендуемое  Гражданский брак/женат/замужем         0  Официальное   

                      region       credits children delinq60plus  
0      Новосибирская область           Нет       Да            0  
1     Кемеровская область юг            Да      Нет            0  
2  Кемеровская область север  Пропуск поля      Нет            0  
3  Кемеровская область север           Нет      Нет            0  
4  Кемеровская область север            Да       Да            0  

[5 rows x 23 columns]

In [40]:
# разобьём категориальные признаки marstatus
h_cat_en, h_categories = df['marstatus'].factorize() # изменяем столбец объектов, присваиваем значения от 0 до кол-ва категорий

In [41]:
h_cat_en

array([0, 1, 1, ..., 3, 3, 3], dtype=int64)

In [42]:
h_categories

Index(['Гражданский брак/женат/замужем', 'Холост', 'Разведен', 'Пропуск поля',
       'Вдова/вдовец'],
      dtype='object')

In [43]:
coded = OneHotEncoder().fit_transform(h_cat_en.reshape(-1,1))

In [44]:
coded.toarray()

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       ...,
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.]])

In [45]:
proxy = pd.DataFrame(coded.toarray(), index = df.index, columns = ['mar','unmar','b_mar', 'skip_mar', 'd_mar'])
# создаём таблицу новых значений из категорий

In [46]:
df = pd.concat([df, proxy], axis = 1)
# добавляем таблицу значений категорий в основную таблицу

In [47]:
# работу
h_cat_en, h_categories = df['jobtype'].factorize()
print(h_cat_en)
print(h_categories)

[0 0 0 ... 2 2 2]
Index(['Официальное', 'Неофициальное', 'Пропуск поля'], dtype='object')


In [48]:
coded = OneHotEncoder().fit_transform(h_cat_en.reshape(-1,1))
coded.toarray()
proxy = pd.DataFrame(coded.toarray(), index = df.index, columns = ['oficial_job','unoficial_job', 'skip_job'])
df = pd.concat([df, proxy], axis = 1)

In [49]:
# кредит
h_cat_en, h_categories = df['credits'].factorize()
print(h_cat_en)
print(h_categories)

[0 1 2 ... 0 0 0]
Index(['Нет', 'Да', 'Пропуск поля'], dtype='object')


In [50]:
coded = OneHotEncoder().fit_transform(h_cat_en.reshape(-1,1))
coded.toarray()
proxy = pd.DataFrame(coded.toarray(), index = df.index, columns = ['no_credits','yes_credits', 'skip_credits'])
df = pd.concat([df, proxy], axis = 1)

In [51]:
# машина
h_cat_en, h_categories = df['auto'].factorize()
print(h_cat_en)
print(h_categories)

[0 1 1 ... 1 1 1]
Index(['Нет', 'Пропуск поля', 'Да'], dtype='object')


In [52]:
coded = OneHotEncoder().fit_transform(h_cat_en.reshape(-1,1))
coded.toarray()
proxy = pd.DataFrame(coded.toarray(), index = df.index, columns = ['no_auto','skip_auto', 'yes_auto'])
df = pd.concat([df, proxy], axis = 1)

In [53]:
# жильё
h_cat_en, h_categories = df['housing'].factorize()
print(h_cat_en)
print(h_categories)

[0 1 0 ... 3 3 3]
Index(['Собственное', 'Живут с родителями', 'Арендуемое', 'Пропуск поля',
       'Муниципальное', 'Долевая собственность'],
      dtype='object')


In [54]:
coded = OneHotEncoder().fit_transform(h_cat_en.reshape(-1,1))
coded.toarray()
proxy = pd.DataFrame(coded.toarray(), index = df.index, columns = ['own_housing','par_housing', 'rented_housing', 'skip_housing', 'municipal_housing', 'sp_housing'])
df = pd.concat([df, proxy], axis = 1)

In [55]:
# дети
h_cat_en, h_categories = df['children'].factorize()
print(h_cat_en)
print(h_categories)

[0 1 1 ... 0 1 1]
Index(['Да', 'Нет', 'Пропуск поля'], dtype='object')


In [56]:
coded = OneHotEncoder().fit_transform(h_cat_en.reshape(-1,1))
coded.toarray()
proxy = pd.DataFrame(coded.toarray(), index = df.index, columns = ['yes_children', 'no_childreng', 'skip_children'])
df = pd.concat([df, proxy], axis = 1)

In [58]:
# регион
h_cat_en, h_categories = df['region'].factorize()
print(h_cat_en)
print(h_categories)

[0 1 2 ... 0 1 2]
Index(['Новосибирская область', 'Кемеровская область юг',
       'Кемеровская область север', 'Алтайский край', 'Красноярский край'],
      dtype='object')


In [59]:
coded = OneHotEncoder().fit_transform(h_cat_en.reshape(-1,1))
coded.toarray()
proxy = pd.DataFrame(coded.toarray(), index = df.index, columns = ['nov','kem_s', 'kem_n', 'alt', 'kras'])
df = pd.concat([df, proxy], axis = 1)

In [61]:
# удалим ненужные столбцы
df = df.drop(['id', 'jobtype', 'housing', 'auto', 'credits', 'marstatus', 'region', 'children', 'gender', 'date_start', 'date_end'], axis = 1)

In [62]:
df.head()

start_year  start_quart  start_month  start_day  end_year  end_quart  \
0        2013            1            1          3      2013          1   
1        2013            1            1          3      2013          1   
2        2013            1            1          3      2013          1   
3        2013            1            1          3      2013          1   
4        2013            1            1          3      2013          1   

   end_month  end_day  loang_term  age  ...  municipal_housing  sp_housing  \
0          1       12           9   44  ...                0.0         0.0   
1          1       17          14   21  ...                0.0         0.0   
2          1       17          14   25  ...                0.0         0.0   
3          1       17          14   47  ...                0.0         0.0   
4          1       17          14   22  ...                0.0         0.0   

   yes_children  no_childreng  skip_children  nov  kem_s  kem_n  alt  kras  
0           1.0           0.0            0.0  1.0    0.0    0.0  0.0   0.0  
1           0.0           1.0            0.0  0.0    1.0    0.0  0.0   0.0  
2           0.0           1.0            0.0  0.0    0.0    1.0  0.0   0.0  
3           0.0           1.0            0.0  0.0    0.0    1.0  0.0   0.0  
4           1.0           0.0            0.0  0.0    0.0    1.0  0.0   0.0  

[5 rows x 40 columns]

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35212 entries, 0 to 35211
Data columns (total 40 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   start_year         35212 non-null  int64  
 1   start_quart        35212 non-null  int64  
 2   start_month        35212 non-null  int64  
 3   start_day          35212 non-null  int64  
 4   end_year           35212 non-null  int64  
 5   end_quart          35212 non-null  int64  
 6   end_month          35212 non-null  int64  
 7   end_day            35212 non-null  int64  
 8   loang_term         35212 non-null  int64  
 9   age                35212 non-null  int64  
 10  regclient          35212 non-null  int64  
 11  delinq60plus       35212 non-null  int64  
 12  mar                35212 non-null  float64
 13  unmar              35212 non-null  float64
 14  b_mar              35212 non-null  float64
 15  skip_mar           35212 non-null  float64
 16  d_mar              352

In [64]:
X = df.drop(['delinq60plus'], axis=1)
Y = df['delinq60plus']

In [65]:
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import GradientBoostingClassifier

In [68]:
sc = StandardScaler()
X_sc = sc.fit_transform(X)

In [69]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_sc, Y, random_state=42)

In [75]:
from sklearn.model_selection import GridSearchCV

In [76]:
gbc = GradientBoostingClassifier()

In [84]:
gbc_params = {'n_estimators': range(1, 10, 2), 'max_depth': range(1, 5)}

In [85]:
gsp = GridSearchCV(gbc, gbc_params, cv = 5, verbose=True, scoring='roc_auc')

In [86]:
gsp.fit(X_sc, Y)

Fitting 5 folds for each of 20 candidates, totalling 100 fits


GridSearchCV(cv=5, estimator=GradientBoostingClassifier(),
             param_grid={'max_depth': range(1, 5),
                         'n_estimators': range(1, 10, 2)},
             scoring='roc_auc', verbose=True)

In [94]:
gsp.best_params_

{'max_depth': 1, 'n_estimators': 7, 'random_state': 1}

In [92]:
gbc_params = {'n_estimators': range(7, 8), 'max_depth': range(1, 2), 'random_state': range(1, 25)}
gsp = GridSearchCV(gbc, gbc_params, cv = 5, verbose=True, scoring='roc_auc')

In [138]:
gbc = GradientBoostingClassifier(n_estimators = 20,
                                max_depth = 6,
                                random_state = 15)

In [139]:
gbc.fit(X_train, y_train)

GradientBoostingClassifier(max_depth=6, n_estimators=20, random_state=15)

In [140]:
from sklearn.metrics import confusion_matrix, precision_score, \
              accuracy_score

In [141]:
pred = gbc.predict(X_test)
accuracy_score(y_test, pred)

0.7672384414404181

In [142]:
confusion_matrix(y_test, pred)

array([[4285, 1180],
       [ 869, 2469]], dtype=int64)

In [143]:
from sklearn.tree import DecisionTreeClassifier

In [153]:
dtclf = DecisionTreeClassifier(max_depth = 1, max_features = 14, random_state = 42)

dtclf.fit(X_train, y_train)
dtclf.score(X_test, y_test)

0.696807906395547

In [148]:
tree_params = {'max_depth': range(1,11), 'max_features': range(3,19)}
tree = DecisionTreeClassifier()

In [149]:
tree_grid = GridSearchCV(tree, tree_params, cv=5)# scoring='roc_auc'

In [152]:
tree_grid.fit(X_sc, Y)
tree_grid.best_params_

{'max_depth': 1, 'max_features': 14}