<a href="https://colab.research.google.com/github/Uliana-Liakh/DS04_onl/blob/main/HWL10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Даны матрицы А

[[-0.05, -0.07,  0.34, -0.42,  0.  , -0.04, -0.33,  0.22,  0.28,
         0.43, -0.2 ,  0.26,  0.1 , -0.8 , -0.62],
       [ 0.62,  0.76,  0.68, -0.36,  0.  ,  0.39,  0.41,  0.81,  0.84,
         0.48,  0.36,  0.11, -0.02, -0.79,  0.37],
       [-0.36, -0.59,  0.68, -0.11,  0.  , -0.4 , -0.78, -0.59, -0.31,
         0.11, -0.38,  0.18,  0.24,  0.23,  0.75],
       [ 0.28,  0.17,  0.87, -0.53,  0.  , -0.39,  0.34, -0.17,  0.15,
        -0.21,  0.34, -0.29, -0.41,  0.68,  0.62],
       [-0.08,  0.07,  0.09, -0.3 ,  0.  , -0.73,  0.14,  0.38,  0.1 ,
        -0.02, -0.55, -0.1 ,  0.31,  0.88,  0.18],
       [-0.4 ,  0.41,  0.1 , -0.33,  0.  , -0.28,  0.1 ,  0.73, -0.25,
         0.21, -0.17, -0.04,  0.08,  0.64, -0.25],
       [ 0.29, -0.35, -0.34,  0.77,  0.  ,  0.03,  0.13,  0.82,  0.78,
         0.64,  0.67, -0.04,  0.36,  0.79,  0.89],
       [ 0.79,  0.56, -0.79,  0.57,  0.  , -0.44, -0.62,  0.69, -0.21,
        -0.34, -0.22,  0.8 , -0.08, -0.54,  0.87],
       [-0.76, -0.18, -0.37, -0.72,  0.  ,  0.46,  0.64,  0.7 , -0.16,
         0.76,  0.31,  0.84,  0.  ,  0.39, -0.1 ],
       [ 0.69,  0.66,  0.62, -0.07,  0.  ,  0.45,  0.47,  0.44,  0.69,
        -0.03,  0.89,  0.19, -0.57, -0.73,  0.52],
       [-0.37, -0.05, -0.29, -0.29,  0.  ,  0.83,  0.42, -0.75,  0.  ,
         0.05, -0.35,  0.36, -0.13, -0.07,  0.04],
       [-0.78, -0.71,  0.66,  0.22,  0.  , -0.67,  0.8 ,  0.2 ,  0.15,
         0.39, -0.6 ,  0.62,  0.22, -0.75,  0.12],
       [-0.65, -0.73,  0.45, -0.56,  0.  ,  0.07,  0.79,  0.75,  0.27,
         0.83, -0.78,  0.85, -0.57,  0.35, -0.69],
       [-0.28, -0.09, -0.32, -0.34,  0.  , -0.55, -0.63,  0.18,  0.46,
        -0.49, -0.43,  0.54, -0.09,  0.84, -0.08],
       [ 0.12,  0.4 ,  0.77,  0.4 ,  0.  ,  0.04,  0.66,  0.3 , -0.6 ,
        -0.48, -0.48,  0.6 ,  0.11, -0.36,  0.14]]

и В

       [-70, -28,  19,  34, -70,  37,  84, -49,  -4, -74,  51,   6,  46,
         75,  42],
       [ 66,  15, -79,  66, -13,   0,  17, -15,   8,  25,  77,  64,  23,
         34,  30],
       [ -1,  34,  67, -13,  -7, -74, -63, -25,  48,  82,  38,  35,  30,
         32, -16],
       [ 74,  20, -53,   1, -28, -23,  73,  15, -27,  42, -62, -74,  51,
         87,  46],
       [ 55,  46,  33,  83,  80,  31,  21, -71,  26, -46,  39, -16,  77,
         29, -35],
       [ 78, -45, -16, -55, -79,  61, -77, -76,  55,  72,  29, -11, -58,
         28,  52],
       [  9, -78, -46,  87, -30, -16,  -5,  44, -30, -16, -26, -48,  -7,
         34, -40],
       [ 61, -47,  18, -16, -61, -55,  25,  37,  55,  66,  -5, -68, -29,
        -22,  40],
       [ -7, -44,  -6,  22,  36,  79, -15, -13,  24,   2,  57,  13, -47,
         27, -22],
       [ 58, -56, -65,  44, -53, -79,  21,  -7, -77,  31,  70,  55,  72,
        -50,  -6],
       [ 64, -29,  16, -61,  63, -52, -34, -19,  13, -74,  68, -66,  58,
          7,  55],
       [-79,  21, -64, -59, -16, -30,   4,   5, -54,   4,  20,  52, -11,
        -20,  -2],
       [-44, -72,  41, -33, -35,  34, -17,  47,   1,  25, -70,  26, -35,
         57, -47],
       [ 53,  38, -55, -24, -42,  33,  74,  32,  83,  79, -25,   2, -27,
        -19,  46],
       [ 11,  29,  10,  18,  39,  -1, -45, -56,  -6,  -7, -46,  10,  23,
          5,   4]]

1 Найдете матрицу последовательного применения операторов А и В
        
2 Примените этот оператор к вектору b
        [ 8.5,  7.8,  2.4, -4.4, -0.6,  7.7, -3.2, -5.3, -4. , -5.6, -3.7,
       -2.2,  8.1, -1.1,  2.3]
    
3 Найдите матрицу обратного отображения 

In [ ]:
import numpy as np

In [ ]:
A = np.array([[-0.05, -0.07,  0.34, -0.42,  0.  , -0.04, -0.33,  0.22,  0.28,
         0.43, -0.2 ,  0.26,  0.1 , -0.8 , -0.62],
       [ 0.62,  0.76,  0.68, -0.36,  0.  ,  0.39,  0.41,  0.81,  0.84,
         0.48,  0.36,  0.11, -0.02, -0.79,  0.37],
       [-0.36, -0.59,  0.68, -0.11,  0.  , -0.4 , -0.78, -0.59, -0.31,
         0.11, -0.38,  0.18,  0.24,  0.23,  0.75],
       [ 0.28,  0.17,  0.87, -0.53,  0.  , -0.39,  0.34, -0.17,  0.15,
        -0.21,  0.34, -0.29, -0.41,  0.68,  0.62],
       [-0.08,  0.07,  0.09, -0.3 ,  0.  , -0.73,  0.14,  0.38,  0.1 ,
        -0.02, -0.55, -0.1 ,  0.31,  0.88,  0.18],
       [-0.4 ,  0.41,  0.1 , -0.33,  0.  , -0.28,  0.1 ,  0.73, -0.25,
         0.21, -0.17, -0.04,  0.08,  0.64, -0.25],
       [ 0.29, -0.35, -0.34,  0.77,  0.  ,  0.03,  0.13,  0.82,  0.78,
         0.64,  0.67, -0.04,  0.36,  0.79,  0.89],
       [ 0.79,  0.56, -0.79,  0.57,  0.  , -0.44, -0.62,  0.69, -0.21,
        -0.34, -0.22,  0.8 , -0.08, -0.54,  0.87],
       [-0.76, -0.18, -0.37, -0.72,  0.  ,  0.46,  0.64,  0.7 , -0.16,
         0.76,  0.31,  0.84,  0.  ,  0.39, -0.1 ],
       [ 0.69,  0.66,  0.62, -0.07,  0.  ,  0.45,  0.47,  0.44,  0.69,
        -0.03,  0.89,  0.19, -0.57, -0.73,  0.52],
       [-0.37, -0.05, -0.29, -0.29,  0.  ,  0.83,  0.42, -0.75,  0.  ,
         0.05, -0.35,  0.36, -0.13, -0.07,  0.04],
       [-0.78, -0.71,  0.66,  0.22,  0.  , -0.67,  0.8 ,  0.2 ,  0.15,
         0.39, -0.6 ,  0.62,  0.22, -0.75,  0.12],
       [-0.65, -0.73,  0.45, -0.56,  0.  ,  0.07,  0.79,  0.75,  0.27,
         0.83, -0.78,  0.85, -0.57,  0.35, -0.69],
       [-0.28, -0.09, -0.32, -0.34,  0.  , -0.55, -0.63,  0.18,  0.46,
        -0.49, -0.43,  0.54, -0.09,  0.84, -0.08],
       [ 0.12,  0.4 ,  0.77,  0.4 ,  0.  ,  0.04,  0.66,  0.3 , -0.6 ,
        -0.48, -0.48,  0.6 ,  0.11, -0.36,  0.14]])
B = np.array([[-70, -28,  19,  34, -70,  37,  84, -49,  -4, -74,  51,   6,  46,
         75,  42],
       [ 66,  15, -79,  66, -13,   0,  17, -15,   8,  25,  77,  64,  23,
         34,  30],
       [ -1,  34,  67, -13,  -7, -74, -63, -25,  48,  82,  38,  35,  30,
         32, -16],
       [ 74,  20, -53,   1, -28, -23,  73,  15, -27,  42, -62, -74,  51,
         87,  46],
       [ 55,  46,  33,  83,  80,  31,  21, -71,  26, -46,  39, -16,  77,
         29, -35],
       [ 78, -45, -16, -55, -79,  61, -77, -76,  55,  72,  29, -11, -58,
         28,  52],
       [  9, -78, -46,  87, -30, -16,  -5,  44, -30, -16, -26, -48,  -7,
         34, -40],
       [ 61, -47,  18, -16, -61, -55,  25,  37,  55,  66,  -5, -68, -29,
        -22,  40],
       [ -7, -44,  -6,  22,  36,  79, -15, -13,  24,   2,  57,  13, -47,
         27, -22],
       [ 58, -56, -65,  44, -53, -79,  21,  -7, -77,  31,  70,  55,  72,
        -50,  -6],
       [ 64, -29,  16, -61,  63, -52, -34, -19,  13, -74,  68, -66,  58,
          7,  55],
       [-79,  21, -64, -59, -16, -30,   4,   5, -54,   4,  20,  52, -11,
        -20,  -2],
       [-44, -72,  41, -33, -35,  34, -17,  47,   1,  25, -70,  26, -35,
         57, -47],
       [ 53,  38, -55, -24, -42,  33,  74,  32,  83,  79, -25,   2, -27,
        -19,  46],
       [ 11,  29,  10,  18,  39,  -1, -45, -56,  -6,  -7, -46,  10,  23,
          5,   4]])

In [ ]:
A@B

array([[ -89.19,  -60.01,   61.83,  -14.51,  -10.12,  -58.24,  -67.57,
          -2.37,  -58.51,    2.48,  116.52,   88.33,   -9.7 ,  -51.71,
         -73.28],
       [  62.35, -167.46,   14.67,  100.73,  -66.45,  -67.12, -105.04,
        -113.32,   13.79,   13.6 ,  247.19,   44.63,   44.35,   84.54,
          21.98],
       [-116.88,  164.21,  104.62,  -85.91,   89.56,  -44.4 ,  -71.4 ,
         -29.89,  -14.46,   58.32, -108.76,  124.64,   31.54,  -66.68,
         -74.76],
       [   6.14,   75.26,   54.55,   61.45,   70.48,  -34.37,  -33.  ,
         -48.28,  107.47,   -5.53,   68.34,   31.54,   52.02,    2.43,
           8.15],
       [ -38.75,   31.33,   -8.63,   59.34,  -26.43,   10.09,  100.04,
         113.26,   64.31,   88.62,  -90.46,   47.74,  -51.74,  -47.18,
         -50.36],
       [  87.99,   -0.72,  -49.51,   18.22,  -63.83,  -75.65,   53.32,
         101.74,   72.82,  133.35,   -0.95,   18.7 ,  -36.81,  -88.56,
           9.01],
       [ 180.97, -120.08,  -74.92,  -19.

In [ ]:
b = np.array([ 8.5,  7.8,  2.4, -4.4, -0.6,  7.7, -3.2, -5.3, -4. , -5.6, -3.7,
       -2.2,  8.1, -1.1,  2.3])

In [ ]:
C = B @ A @ b
C

array([-2653.55 , -1726.251,  -539.132,  -654.974, -3038.508,  1516.034,
         939.057,  1777.987,   -18.045, -1214.986,   210.535,   472.063,
        -562.658,  -947.503,  -513.84 ])

In [ ]:
np.linalg.inv(A@B)

array([[ 2.44938187e+12, -7.89226240e+12,  2.85442013e+12,
        -6.90299199e+12,  1.10250210e+13, -3.92811614e+11,
        -6.00039018e+11, -1.12584336e+12,  1.72526089e+11,
         1.18950654e+13,  8.77253971e+11, -1.70030751e+12,
         2.25809483e+11, -3.27045667e+12, -6.88979228e+11],
       [ 3.51275236e+11, -1.13185958e+12,  4.09363324e+11,
        -9.89984519e+11,  1.58114048e+12, -5.63346181e+10,
        -8.60538937e+10, -1.61461509e+11,  2.47426272e+10,
         1.70591689e+12,  1.25810352e+11, -2.43847613e+11,
         3.23842028e+10, -4.69028716e+11, -9.88091498e+10],
       [-4.75243309e+11,  1.53130263e+12, -5.53831186e+11,
         1.33935863e+12, -2.13913865e+12,  7.62155927e+10,
         1.16423058e+11,  2.18442674e+11, -3.34745146e+10,
        -2.30794973e+12, -1.70209915e+11,  3.29903547e+11,
        -4.38128684e+10,  6.34553013e+11,  1.33679755e+11],
       [-1.58028331e+12,  5.09190122e+12, -1.84160443e+12,
         4.45364733e+12, -7.11308302e+12,  2.53432772