<a href="https://colab.research.google.com/github/Uliana-Liakh/DS04_onl/blob/main/HWL9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Создайте массивы 
a = [1., 2., 3., 4., 5., 6., 7., 8., 9.]
b = [9., 8., 7., 6., 5., 4., 3., 2., 1.]
с помощью конструктора np.linspace

2. Сравните массивы между собой (выполните операции <, =, >)

3. Выполните поэлементное умножение массивов 

4. Найдите среднее значение массива полученного на шаге 3

5. вычтите полученное среднее на шаге 4 из массива, полученного на шаге 3

6. найдите скалярное произведение массивов/векторов a и b

подсказка - скалярное произведение можно посчитать так np.dot(a,b)

7. преобразуйте массивы a и b в двумерные массивы размером 3х3

8. примените к полученным на шаге 7 массивам функцию dot. Как вы думаете - что вы получили в результате?



In [ ]:
import numpy as np

In [ ]:
a = np.linspace(1, 9, 9)
a

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
b = np.linspace(9, 1, 9)
b

array([9., 8., 7., 6., 5., 4., 3., 2., 1.])

In [ ]:
a < b

array([ True,  True,  True,  True, False, False, False, False, False])

In [ ]:
a == b

array([False, False, False, False,  True, False, False, False, False])

In [ ]:
a > b

array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
a*b

array([ 9., 16., 21., 24., 25., 24., 21., 16.,  9.])

In [ ]:
c = a*b
d = c.mean()
d

18.333333333333332

In [ ]:
c-d

array([-9.33333333, -2.33333333,  2.66666667,  5.66666667,  6.66666667,
        5.66666667,  2.66666667, -2.33333333, -9.33333333])

In [ ]:
np.dot(a,b)

165.0

In [ ]:
a.shape = (3,3)
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
a12 = a.reshape(3,3)

In [ ]:
b.shape = (3,3)
b

array([[9., 8., 7.],
       [6., 5., 4.],
       [3., 2., 1.]])

In [ ]:
b12 = b.reshape(3,3)

In [ ]:
np.dot(a,b) #Умножение матриц (настоящее)

array([[ 30.,  24.,  18.],
       [ 84.,  69.,  54.],
       [138., 114.,  90.]])

In [ ]:
a12@b12

array([[ 30.,  24.,  18.],
       [ 84.,  69.,  54.],
       [138., 114.,  90.]])

Проверка задания с тремя векторами:

In [ ]:
a1=np.array([55, -10, 14, 458, 33, -21, 5])
b1=np.array([89, 15, 9, 45, -22, -8, 18])
c1=np.array([42, -70, 38, 1742, 176, -68, -16])

In [ ]:
2*(a1+b1)

array([ 288,   10,   46, 1006,   22,  -58,   46])

In [ ]:
np.dot(a1,c1)+np.dot(b1,4*c1)

1119750

In [ ]:
a12.T #transponirovanaya

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])