In [3]:
import numpy as np

Даны матрицы А

[[-0.05, -0.07,  0.34, -0.42,  0.  , -0.04, -0.33,  0.22,  0.28,
         0.43, -0.2 ,  0.26,  0.1 , -0.8 , -0.62],
       [ 0.62,  0.76,  0.68, -0.36,  0.  ,  0.39,  0.41,  0.81,  0.84,
         0.48,  0.36,  0.11, -0.02, -0.79,  0.37],
       [-0.36, -0.59,  0.68, -0.11,  0.  , -0.4 , -0.78, -0.59, -0.31,
         0.11, -0.38,  0.18,  0.24,  0.23,  0.75],
       [ 0.28,  0.17,  0.87, -0.53,  0.  , -0.39,  0.34, -0.17,  0.15,
        -0.21,  0.34, -0.29, -0.41,  0.68,  0.62],
       [-0.08,  0.07,  0.09, -0.3 ,  0.  , -0.73,  0.14,  0.38,  0.1 ,
        -0.02, -0.55, -0.1 ,  0.31,  0.88,  0.18],
       [-0.4 ,  0.41,  0.1 , -0.33,  0.  , -0.28,  0.1 ,  0.73, -0.25,
         0.21, -0.17, -0.04,  0.08,  0.64, -0.25],
       [ 0.29, -0.35, -0.34,  0.77,  0.  ,  0.03,  0.13,  0.82,  0.78,
         0.64,  0.67, -0.04,  0.36,  0.79,  0.89],
       [ 0.79,  0.56, -0.79,  0.57,  0.  , -0.44, -0.62,  0.69, -0.21,
        -0.34, -0.22,  0.8 , -0.08, -0.54,  0.87],
       [-0.76, -0.18, -0.37, -0.72,  0.  ,  0.46,  0.64,  0.7 , -0.16,
         0.76,  0.31,  0.84,  0.  ,  0.39, -0.1 ],
       [ 0.69,  0.66,  0.62, -0.07,  0.  ,  0.45,  0.47,  0.44,  0.69,
        -0.03,  0.89,  0.19, -0.57, -0.73,  0.52],
       [-0.37, -0.05, -0.29, -0.29,  0.  ,  0.83,  0.42, -0.75,  0.  ,
         0.05, -0.35,  0.36, -0.13, -0.07,  0.04],
       [-0.78, -0.71,  0.66,  0.22,  0.  , -0.67,  0.8 ,  0.2 ,  0.15,
         0.39, -0.6 ,  0.62,  0.22, -0.75,  0.12],
       [-0.65, -0.73,  0.45, -0.56,  0.  ,  0.07,  0.79,  0.75,  0.27,
         0.83, -0.78,  0.85, -0.57,  0.35, -0.69],
       [-0.28, -0.09, -0.32, -0.34,  0.  , -0.55, -0.63,  0.18,  0.46,
        -0.49, -0.43,  0.54, -0.09,  0.84, -0.08],
       [ 0.12,  0.4 ,  0.77,  0.4 ,  0.  ,  0.04,  0.66,  0.3 , -0.6 ,
        -0.48, -0.48,  0.6 ,  0.11, -0.36,  0.14]]

и В

       [-70, -28,  19,  34, -70,  37,  84, -49,  -4, -74,  51,   6,  46,
         75,  42],
       [ 66,  15, -79,  66, -13,   0,  17, -15,   8,  25,  77,  64,  23,
         34,  30],
       [ -1,  34,  67, -13,  -7, -74, -63, -25,  48,  82,  38,  35,  30,
         32, -16],
       [ 74,  20, -53,   1, -28, -23,  73,  15, -27,  42, -62, -74,  51,
         87,  46],
       [ 55,  46,  33,  83,  80,  31,  21, -71,  26, -46,  39, -16,  77,
         29, -35],
       [ 78, -45, -16, -55, -79,  61, -77, -76,  55,  72,  29, -11, -58,
         28,  52],
       [  9, -78, -46,  87, -30, -16,  -5,  44, -30, -16, -26, -48,  -7,
         34, -40],
       [ 61, -47,  18, -16, -61, -55,  25,  37,  55,  66,  -5, -68, -29,
        -22,  40],
       [ -7, -44,  -6,  22,  36,  79, -15, -13,  24,   2,  57,  13, -47,
         27, -22],
       [ 58, -56, -65,  44, -53, -79,  21,  -7, -77,  31,  70,  55,  72,
        -50,  -6],
       [ 64, -29,  16, -61,  63, -52, -34, -19,  13, -74,  68, -66,  58,
          7,  55],
       [-79,  21, -64, -59, -16, -30,   4,   5, -54,   4,  20,  52, -11,
        -20,  -2],
       [-44, -72,  41, -33, -35,  34, -17,  47,   1,  25, -70,  26, -35,
         57, -47],
       [ 53,  38, -55, -24, -42,  33,  74,  32,  83,  79, -25,   2, -27,
        -19,  46],
       [ 11,  29,  10,  18,  39,  -1, -45, -56,  -6,  -7, -46,  10,  23,
          5,   4]]

1 Найдете матрицу последовательного применения операторов А и В
        
2 Примените этот оператор к вектору b
        [ 8.5,  7.8,  2.4, -4.4, -0.6,  7.7, -3.2, -5.3, -4. , -5.6, -3.7,
       -2.2,  8.1, -1.1,  2.3]
    
3 Найдите матрицу обратного отображения     



In [19]:
A = np.array([[-0.05, -0.07, 0.34, -0.42, 0. , -0.04, -0.33, 0.22, 0.28, 0.43, -0.2 , 0.26, 0.1 , -0.8 , -0.62], [ 0.62, 0.76, 0.68, -0.36, 0. , 0.39, 0.41, 0.81, 0.84, 0.48, 0.36, 0.11, -0.02, -0.79, 0.37], [-0.36, -0.59, 0.68, -0.11, 0. , -0.4 , -0.78, -0.59, -0.31, 0.11, -0.38, 0.18, 0.24, 0.23, 0.75], [ 0.28, 0.17, 0.87, -0.53, 0. , -0.39, 0.34, -0.17, 0.15, -0.21, 0.34, -0.29, -0.41, 0.68, 0.62], [-0.08, 0.07, 0.09, -0.3 , 0. , -0.73, 0.14, 0.38, 0.1 , -0.02, -0.55, -0.1 , 0.31, 0.88, 0.18], [-0.4 , 0.41, 0.1 , -0.33, 0. , -0.28, 0.1 , 0.73, -0.25, 0.21, -0.17, -0.04, 0.08, 0.64, -0.25], [ 0.29, -0.35, -0.34, 0.77, 0. , 0.03, 0.13, 0.82, 0.78, 0.64, 0.67, -0.04, 0.36, 0.79, 0.89], [ 0.79, 0.56, -0.79, 0.57, 0. , -0.44, -0.62, 0.69, -0.21, -0.34, -0.22, 0.8 , -0.08, -0.54, 0.87], [-0.76, -0.18, -0.37, -0.72, 0. , 0.46, 0.64, 0.7 , -0.16, 0.76, 0.31, 0.84, 0. , 0.39, -0.1 ], [ 0.69, 0.66, 0.62, -0.07, 0. , 0.45, 0.47, 0.44, 0.69, -0.03, 0.89, 0.19, -0.57, -0.73, 0.52], [-0.37, -0.05, -0.29, -0.29, 0. , 0.83, 0.42, -0.75, 0. , 0.05, -0.35, 0.36, -0.13, -0.07, 0.04], [-0.78, -0.71, 0.66, 0.22, 0. , -0.67, 0.8 , 0.2 , 0.15, 0.39, -0.6 , 0.62, 0.22, -0.75, 0.12], [-0.65, -0.73, 0.45, -0.56, 0. , 0.07, 0.79, 0.75, 0.27, 0.83, -0.78, 0.85, -0.57, 0.35, -0.69], [-0.28, -0.09, -0.32, -0.34, 0. , -0.55, -0.63, 0.18, 0.46, -0.49, -0.43, 0.54, -0.09, 0.84, -0.08], [ 0.12, 0.4 , 0.77, 0.4 , 0. , 0.04, 0.66, 0.3 , -0.6 , -0.48, -0.48, 0.6 , 0.11, -0.36, 0.14]])


In [5]:
np.linalg.det(A)

0.0

In [6]:
B =  np.array([[-70, -28,  19,  34, -70,  37,  84, -49,  -4, -74,  51,   6,  46,
     75,  42],
   [ 66,  15, -79,  66, -13,   0,  17, -15,   8,  25,  77,  64,  23,
     34,  30],
   [ -1,  34,  67, -13,  -7, -74, -63, -25,  48,  82,  38,  35,  30,
     32, -16],
   [ 74,  20, -53,   1, -28, -23,  73,  15, -27,  42, -62, -74,  51,
     87,  46],
   [ 55,  46,  33,  83,  80,  31,  21, -71,  26, -46,  39, -16,  77,
     29, -35],
   [ 78, -45, -16, -55, -79,  61, -77, -76,  55,  72,  29, -11, -58,
     28,  52],
   [  9, -78, -46,  87, -30, -16,  -5,  44, -30, -16, -26, -48,  -7,
     34, -40],
   [ 61, -47,  18, -16, -61, -55,  25,  37,  55,  66,  -5, -68, -29,
    -22,  40],
   [ -7, -44,  -6,  22,  36,  79, -15, -13,  24,   2,  57,  13, -47,
     27, -22],
   [ 58, -56, -65,  44, -53, -79,  21,  -7, -77,  31,  70,  55,  72,
    -50,  -6],
   [ 64, -29,  16, -61,  63, -52, -34, -19,  13, -74,  68, -66,  58,
      7,  55],
   [-79,  21, -64, -59, -16, -30,   4,   5, -54,   4,  20,  52, -11,
    -20,  -2],
   [-44, -72,  41, -33, -35,  34, -17,  47,   1,  25, -70,  26, -35,
     57, -47],
   [ 53,  38, -55, -24, -42,  33,  74,  32,  83,  79, -25,   2, -27,
    -19,  46],
   [ 11,  29,  10,  18,  39,  -1, -45, -56,  -6,  -7, -46,  10,  23,
      5,   4]])

In [7]:
np.linalg.det(B)

-5.424319762396377e+30

In [8]:
C = B @ A
C

array([[-152.16, -146.84,  -18.98,   25.04,    0.  ,    2.66,   49.25,
         -31.4 ,  -12.15,   16.34,  -69.31,   44.7 ,    8.12,  268.88,
          11.47],
       [ -41.07,    7.27,   96.26,  -79.17,    0.  ,   45.74,  195.08,
          64.73,  110.  ,   51.44,  -21.08,  108.85,  -59.48,  -70.56,
         -45.39],
       [ -66.13,  -51.06,  126.27, -126.24,    0.  ,   77.44,   62.72,
         -63.95,   66.04,   45.24,  -13.64,  129.95,  -73.86, -136.19,
          12.87],
       [ 150.69,   74.48,   -2.2 ,   26.23,    0.  ,   10.28,  -47.51,
         205.35,  159.23,   -3.39,   73.64,   59.44,  -55.57,   16.72,
         -21.41],
       [-147.49, -101.5 ,  142.29, -243.12,    0.  ,  -42.65,   82.3 ,
          55.02,  104.63,  157.77,  -91.  ,   11.68,  -13.73,  245.76,
         -64.53],
       [-100.06,   68.9 ,   36.  ,  -96.4 ,    0.  ,  150.66,   25.02,
         -78.2 ,  -81.25,  -37.34,   39.61,   36.66,  -24.81, -158.59,
        -198.39],
       [  83.27,   16.02, -110.72,   14.

In [9]:
np.linalg.det(C)

0.0

In [10]:
b  = np.array([ 8.5, 7.8, 2.4, -4.4, -0.6, 7.7, -3.2, -5.3, -4. , -5.6, -3.7, -2.2, 8.1, -1.1, 2.3])
b

array([ 8.5,  7.8,  2.4, -4.4, -0.6,  7.7, -3.2, -5.3, -4. , -5.6, -3.7,
       -2.2,  8.1, -1.1,  2.3])

In [15]:
u = A@b
u

array([ -1.821,   5.748,   2.047,   2.249,  -2.757,  -4.945, -14.001,
         5.363, -15.07 ,   3.517,   5.406, -19.376, -24.94 ,  -6.057,
         7.987])

In [16]:
u = B@u
u #образ вектора b

array([-2653.55 , -1726.251,  -539.132,  -654.974, -3038.508,  1516.034,
         939.057,  1777.987,   -18.045, -1214.986,   210.535,   472.063,
        -562.658,  -947.503,  -513.84 ])

In [18]:
C @ b

array([-2653.55 , -1726.251,  -539.132,  -654.974, -3038.508,  1516.034,
         939.057,  1777.987,   -18.045, -1214.986,   210.535,   472.063,
        -562.658,  -947.503,  -513.84 ])

In [17]:
B @ A @ b

array([-2653.55 , -1726.251,  -539.132,  -654.974, -3038.508,  1516.034,
         939.057,  1777.987,   -18.045, -1214.986,   210.535,   472.063,
        -562.658,  -947.503,  -513.84 ])

In [ ]:
import numpy as np

def is_invertible(matrix):
    determinant = np.linalg.det(matrix)
    return determinant != 0

def inverse_matrix(matrix):
    if is_invertible(matrix):
        return np.linalg.inv(matrix)
    else:
        return None

# Пример использования:
A = np.array([[7, 4, -4], [2, -4, -5], [-2, 5, 1]])
if is_invertible(A):
    A_inv = inverse_matrix(A)
    print("Обратная матрица:\n", A_inv)
else:
    print("Матрица не имеет обратной.")

Обратная матрица:
 [[ 0.12280702 -0.14035088 -0.21052632]
 [ 0.04678363 -0.00584795  0.15789474]
 [ 0.01169591 -0.25146199 -0.21052632]]
