1. Создайте массивы 
a = [1., 2., 3., 4., 5., 6., 7., 8., 9.]
b = [9., 8., 7., 6., 5., 4., 3., 2., 1.]
с помощью конструктора np.linspace

2. Сравните массивы между собой (выполните операции <, =, >)

3. Выполните поэлементное умножение массивов 

4. Найдите среднее значение массива полученного на шаге 3

5. вычтите полученное среднее на шаге 4 из массива, полученного на шаге 3

6. найдите скалярное произведение массивов/векторов a и b

подсказка - скалярное произведение можно посчитать так np.dot(a,b)

7. преобразуйте массивы a и b в двумерные массивы размером 3х3

8. примените к полученным на шаге 7 массивам функцию dot. Как вы думаете - что вы получили в результате?



In [1]:
import numpy as np

In [2]:
# Создайте массивы a = [1., 2., 3., 4., 5., 6., 7., 8., 9.] b = [9., 8., 7., 6., 5., 4., 3., 2., 1.]
# с помощью конструктора np.linspace
a = np.linspace(1, 9, 9)
b = np.linspace(9, 1, 9)

In [3]:
# Сравните массивы между собой (выполните операции <, =, >)
print (a > b)
print (a < b)
print (a == b)

[False False False False False  True  True  True  True]
[ True  True  True  True False False False False False]
[False False False False  True False False False False]


In [4]:
# Выполните поэлементное умножение массивов
c = a * b
print(c)

[ 9. 16. 21. 24. 25. 24. 21. 16.  9.]


In [5]:
# Найдите среднее значение массива полученного на шаге 3
sred = c.mean()
print(sred)

18.333333333333332


In [6]:
# вычтите полученное среднее на шаге 4 из массива, полученного на шаге 3
print(c - sred)

[-9.33333333 -2.33333333  2.66666667  5.66666667  6.66666667  5.66666667
  2.66666667 -2.33333333 -9.33333333]


In [7]:
# найдите скалярное произведение массивов/векторов a и b
print(np.dot(a,b))

165.0


In [8]:
# преобразуйте массивы a и b в двумерные массивы размером 3х3
a1 = a.reshape(3,3)
print(a1)
b1 = b.reshape(3,3)
print(b1)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[9. 8. 7.]
 [6. 5. 4.]
 [3. 2. 1.]]


In [9]:
# примените к полученным на шаге 7 массивам функцию dot. Как вы думаете - что вы получили в результате?
print(np.dot(a1,b1))
# получили умножение матриц друг на друга (поэлементное, строка умножается на столбец)

[[ 30.  24.  18.]
 [ 84.  69.  54.]
 [138. 114.  90.]]


In [11]:
# задание из презентации
a = np.array([55, -10, 14, 458, 33, -21, 5])
b = np.array([89, 15, 9, 45, -22, -8, 18])
c = np.array([42, -70, 38, 1742, 176, -68, -16])

In [12]:
# 2*(a+b)
sum_a_b = a + b
rez1 = 2 * sum_a_b
print(rez1)

[ 288   10   46 1006   22  -58   46]


In [13]:
# ac+b(4c)
c_4 = 4 * c
ac = np.dot(a, c)
b4c = np.dot(b, c_4)
rez2 = ac + b4c
print(rez2)

1119750


In [14]:
# или так
print(np.dot(a, c) + np.dot(b, 4 * c))

1119750
