В приложенном файле хранятся обучающий набор для модели линейной регресии
последний столбец файла содернжит значения целевой фкнкции.
1. Прочитайте данные из файла в nympy-массив с помощью функции np.loadtxt('linreg_4.txt')
2. Отделите независимые переменные от целевой переменной
3. адаптируйте написанный на уроке код градиентного спуска для нахождения коэффициентов линейной модели
вида y = h0 + h1*x1 + h2*x2 + h3*x3
4. Найдите коэффициенты h методом градиентного спуска.


In [10]:
import numpy as np

In [11]:
data = np.loadtxt('linreg_4.txt')

In [12]:
data.shape

(100, 4)

In [13]:
X_ = data[:, :-1]  # Все колонки, кроме последней
# Добавление столбца единиц (для удобства вычислений)
X = np.c_[np.ones((100,1)), X_]
X

array([[1.        , 1.2995489 , 1.39046002, 0.34551026],
       [1.        , 0.55133973, 0.76100408, 0.61751073],
       [1.        , 1.36703752, 1.08220897, 1.48202247],
       [1.        , 0.66075662, 0.53680347, 1.79729948],
       [1.        , 1.36860863, 0.59988975, 1.45333969],
       [1.        , 0.28368774, 0.74663786, 0.17834055],
       [1.        , 0.1676704 , 0.63951162, 0.19793459],
       [1.        , 0.95762449, 0.64134092, 1.44930468],
       [1.        , 1.14202085, 0.46563185, 1.32799891],
       [1.        , 1.79892507, 0.64081693, 0.10252574],
       [1.        , 0.90939904, 0.14701733, 1.17305202],
       [1.        , 0.26396804, 0.8940012 , 0.42886885],
       [1.        , 0.80213424, 1.70847004, 0.19117915],
       [1.        , 1.07404154, 0.0775781 , 0.95873388],
       [1.        , 0.2887978 , 0.62076949, 0.98057211],
       [1.        , 1.87130211, 0.89764414, 0.64148006],
       [1.        , 1.88533575, 1.07126691, 0.84276499],
       [1.        , 0.61320633,

In [16]:
y_ = data[:, -1]   # Последняя колонка
y = y_.reshape(100,1)
y

array([[ 6.59921909],
       [ 6.49794507],
       [ 9.85891938],
       [11.8677346 ],
       [12.53867434],
       [ 3.71226365],
       [ 2.7758983 ],
       [11.67240193],
       [11.62869211],
       [ 6.51132204],
       [10.54753932],
       [ 4.56975022],
       [ 4.95632954],
       [ 9.13098119],
       [ 5.58599655],
       [ 9.90419046],
       [ 9.99334692],
       [ 4.21243406],
       [ 5.00662058],
       [12.23517436],
       [ 5.5657149 ],
       [ 6.91802888],
       [ 8.08739893],
       [ 4.64648455],
       [ 5.09666668],
       [ 8.39276296],
       [ 7.10791744],
       [ 5.81065217],
       [ 6.819838  ],
       [ 8.29931442],
       [ 8.61942638],
       [ 9.83004162],
       [10.22453454],
       [ 5.07050944],
       [ 5.67053739],
       [ 9.76487048],
       [10.22725585],
       [ 7.99190628],
       [10.38333587],
       [13.71740949],
       [ 6.65394841],
       [ 3.56505285],
       [11.31303505],
       [ 0.70609735],
       [ 6.70851986],
       [ 5

In [19]:
# устанавливаем значения для lr и количества итераций
lr = 0.1
iters = 100
m = 100

# инициализируем начальные значения параметров
h = np.random.randn(4,1)
# применяем градиентный спуск
for i in range(iters):
    gradient = (2/m)*X.T @ (X @ h - y) 
    h = h - lr * gradient

In [20]:
h

array([[ 2.15996658],
       [ 3.25157053],
       [-1.28456863],
       [ 3.89399774]])