В приложенном файле хранятся обучающий набор для модели линейной регресии
последний столбец файла содернжит значения целевой фкнкции.
1. Прочитайте данные из файла в nympy-массив с помощью функции np.loadtxt('linreg_4.txt')
2. Отделите независимые переменные от целевой переменной
3. адаптируйте написанный на уроке код градиентного спуска для нахождения коэффициентов линейной модели
вида y = h0 + h1*x1 + h2*x2 + h3*x3
4. Найдите коэффициенты h методом градиентного спуска.


In [173]:
import numpy as np
data = np.loadtxt('drive/MyDrive/ColabNotebooks/Homeworks/linreg_4.txt') #1 подгружал данные из диска

In [171]:
'''data = ([[ 1.2995489 ,  1.39046002,  0.34551026,  6.59921909],
       [ 0.55133973,  0.76100408,  0.61751073,  6.49794507],
       [ 1.36703752,  1.08220897,  1.48202247,  9.85891938],
       [ 0.66075662,  0.53680347,  1.79729948, 11.8677346 ],
       [ 1.36860863,  0.59988975,  1.45333969, 12.53867434],
       [ 0.28368774,  0.74663786,  0.17834055,  3.71226365],
       [ 0.1676704 ,  0.63951162,  0.19793459,  2.7758983 ],
       [ 0.95762449,  0.64134092,  1.44930468, 11.67240193],
       [ 1.14202085,  0.46563185,  1.32799891, 11.62869211],
       [ 1.79892507,  0.64081693,  0.10252574,  6.51132204],
       [ 0.90939904,  0.14701733,  1.17305202, 10.54753932],
       [ 0.26396804,  0.8940012 ,  0.42886885,  4.56975022],
       [ 0.80213424,  1.70847004,  0.19117915,  4.95632954],
       [ 1.07404154,  0.0775781 ,  0.95873388,  9.13098119],
       [ 0.2887978 ,  0.62076949,  0.98057211,  5.58599655],
       [ 1.87130211,  0.89764414,  0.64148006,  9.90419046],
       [ 1.88533575,  1.07126691,  0.84276499,  9.99334692],
       [ 0.61320633,  1.97711409,  0.5294924 ,  4.21243406],
       [ 0.37442475,  0.95855511,  0.60952   ,  5.00662058],
       [ 1.90218982,  0.40603965,  1.03288188, 12.23517436],
       [ 0.70914797,  0.34531127,  0.31365964,  5.5657149 ],
       [ 0.72542155,  1.13864541,  0.69154681,  6.91802888],
       [ 1.19859224,  1.71062163,  1.47066325,  8.08739893],
       [ 0.42946661,  1.99256902,  1.01244225,  4.64648455],
       [ 0.15100032,  1.5355898 ,  1.31605439,  5.09666668],
       [ 1.31925907,  1.65990904,  0.90869617,  8.39276296],
       [ 0.66617394,  0.92400571,  1.25999604,  7.10791744],
       [ 0.05986516,  1.18637241,  1.26619032,  5.81065217],
       [ 0.88541468,  0.78575745,  0.96770101,  6.819838  ],
       [ 1.81311102,  0.35268681,  0.29261411,  8.29931442],
       [ 1.16267119,  0.53508364,  0.76715654,  8.61942638],
       [ 0.61045832,  1.21375481,  1.82673521,  9.83004162],
       [ 0.30728765,  0.28552291,  1.8000563 , 10.22453454],
       [ 1.50937344,  0.54747438,  0.10579019,  5.07050944],
       [ 1.74089276,  1.98098697,  0.39298261,  5.67053739],
       [ 1.4423044 ,  1.85790534,  1.57974113,  9.76487048],
       [ 1.23412481,  0.67511662,  1.05752096, 10.22725585],
       [ 1.79700485,  0.75397413,  0.18320983,  7.99190628],
       [ 1.24034153,  0.29835946,  1.13485469, 10.38333587],
       [ 1.81862153,  0.56151358,  1.91536657, 13.71740949],
       [ 0.72230546,  0.30428407,  0.62519493,  6.65394841],
       [ 0.90487772,  0.88342309,  0.09675557,  3.56505285],
       [ 1.97711352,  0.02480173,  0.96364984, 11.31303505],
       [ 0.17629326,  0.97611444,  0.27456474,  0.70609735],
       [ 0.45264505,  0.2627081 ,  0.84132295,  6.70851986],
       [ 0.50161463,  0.79380719,  1.10091456,  5.94281218],
       [ 1.03297479,  1.48088316,  0.67258442,  5.43083964],
       [ 0.50189688,  0.33151862,  1.90020367, 12.33202755],
       [ 0.18274992,  1.37227228,  0.81014742,  4.25066076],
       [ 0.32819176,  1.05396019,  0.45062735,  3.30255508],
       [ 1.35258034,  0.46342483,  1.10553466, 10.5884693 ],
       [ 1.42197493,  0.66837975,  0.51996919,  6.38350553],
       [ 0.35254015,  1.94718016,  1.77418618,  7.20680806],
       [ 1.20322981,  0.74659239,  0.69026823,  7.42508035],
       [ 1.43745166,  1.36612999,  0.98982262, 11.51960679],
       [ 1.75821237,  0.96865079,  1.71916407, 12.9475192 ],
       [ 0.54113023,  1.44127098,  0.64617862,  3.8441174 ],
       [ 1.4089363 ,  1.7789933 ,  1.74281202,  9.6778393 ],
       [ 0.70732718,  0.74619811,  1.23968008,  7.53274644],
       [ 0.89578841,  1.60042   ,  0.29180001,  5.34889366],
       [ 0.1773052 ,  1.62954624,  1.26928793,  5.67700515],
       [ 1.73103756,  0.2445565 ,  1.90490106, 14.4954816 ],
       [ 0.43986795,  0.35175663,  0.97583292,  5.70654902],
       [ 1.73243985,  0.28883303,  0.98721235, 11.26608162],
       [ 0.95126931,  0.2636241 ,  1.86911715, 13.16951198],
       [ 1.46181248,  1.26631269,  0.58157249,  7.03586034],
       [ 1.6261582 ,  0.02581814,  1.57219281, 12.98342907],
       [ 0.63764905,  0.80250071,  0.25727437,  3.92684793],
       [ 0.93434367,  0.12233874,  1.19109012,  9.89744678],
       [ 1.39979489,  0.10290196,  1.79032361, 12.5306734 ],
       [ 0.25477896,  1.4970141 ,  1.57674557,  5.36983831],
       [ 0.50995853,  0.31337026,  1.71391769, 10.17257889],
       [ 1.95471795,  1.26154056,  0.70193712,  9.80953616],
       [ 1.07798817,  0.73855354,  0.72479412,  7.41048997],
       [ 1.15651598,  0.60691547,  1.97124051, 11.81786194],
       [ 0.27189934,  0.22599121,  1.9405882 , 10.38518027],
       [ 0.29119164,  1.60136951,  1.32706348,  6.21816705],
       [ 0.82141157,  0.89782393,  0.74221062,  6.13448068],
       [ 1.30940122,  0.06688523,  1.459205  , 12.17805763],
       [ 0.05274166,  0.17749848,  0.18941337,  2.94443937],
       [ 1.93442897,  1.36323432,  1.60332624, 14.3008556 ],
       [ 0.61263724,  1.62810899,  0.94537978,  5.95549454],
       [ 0.65745024,  1.80112734,  1.52186565,  7.47128055],
       [ 1.59144144,  0.63309269,  1.17525146, 10.88366454],
       [ 1.09305888,  0.36566295,  0.04684474,  6.4015056 ],
       [ 0.38323704,  0.73292325,  1.91961837, 10.28262761],
       [ 1.57041813,  1.35145022,  1.88998939, 14.62253969],
       [ 1.09591749,  0.96526728,  1.9112552 , 12.88295801],
       [ 0.30362283,  1.19724105,  0.92577138,  5.68860389],
       [ 0.86298707,  1.69912328,  1.46327799,  9.6750133 ],
       [ 0.93994726,  0.08572623,  1.38725924,  9.7505999 ],
       [ 0.34874923,  1.79152125,  0.5980568 ,  3.91143326],
       [ 0.10496407,  1.58081769,  1.71518274,  5.40932527],
       [ 1.75175742,  0.40380943,  1.07729703, 11.85835765],
       [ 1.79542698,  1.91640769,  0.196494  ,  7.63904784],
       [ 1.59094159,  0.18141751,  0.01513297,  7.0696352 ],
       [ 1.53593666,  0.38918709,  1.10139744, 11.76287225],
       [ 0.25221691,  0.61694851,  1.64706958,  9.55608951],
       [ 1.53660077,  0.23408882,  1.36204721, 11.69226186],
       [ 1.40079392,  0.80520623,  1.22693379, 10.03240249]])
       '''

In [172]:
data

[[1.2995489, 1.39046002, 0.34551026, 6.59921909],
 [0.55133973, 0.76100408, 0.61751073, 6.49794507],
 [1.36703752, 1.08220897, 1.48202247, 9.85891938],
 [0.66075662, 0.53680347, 1.79729948, 11.8677346],
 [1.36860863, 0.59988975, 1.45333969, 12.53867434],
 [0.28368774, 0.74663786, 0.17834055, 3.71226365],
 [0.1676704, 0.63951162, 0.19793459, 2.7758983],
 [0.95762449, 0.64134092, 1.44930468, 11.67240193],
 [1.14202085, 0.46563185, 1.32799891, 11.62869211],
 [1.79892507, 0.64081693, 0.10252574, 6.51132204],
 [0.90939904, 0.14701733, 1.17305202, 10.54753932],
 [0.26396804, 0.8940012, 0.42886885, 4.56975022],
 [0.80213424, 1.70847004, 0.19117915, 4.95632954],
 [1.07404154, 0.0775781, 0.95873388, 9.13098119],
 [0.2887978, 0.62076949, 0.98057211, 5.58599655],
 [1.87130211, 0.89764414, 0.64148006, 9.90419046],
 [1.88533575, 1.07126691, 0.84276499, 9.99334692],
 [0.61320633, 1.97711409, 0.5294924, 4.21243406],
 [0.37442475, 0.95855511, 0.60952, 5.00662058],
 [1.90218982, 0.40603965, 1.03288188,

In [156]:
#2 отделяем целевую переменную (последнее значение в каждом векторе)
Y = data[:, 3:4] # срез всех строк и последнего столбца
Y # целевая переменная

array([[ 6.59921909],
       [ 6.49794507],
       [ 9.85891938],
       [11.8677346 ],
       [12.53867434],
       [ 3.71226365],
       [ 2.7758983 ],
       [11.67240193],
       [11.62869211],
       [ 6.51132204],
       [10.54753932],
       [ 4.56975022],
       [ 4.95632954],
       [ 9.13098119],
       [ 5.58599655],
       [ 9.90419046],
       [ 9.99334692],
       [ 4.21243406],
       [ 5.00662058],
       [12.23517436],
       [ 5.5657149 ],
       [ 6.91802888],
       [ 8.08739893],
       [ 4.64648455],
       [ 5.09666668],
       [ 8.39276296],
       [ 7.10791744],
       [ 5.81065217],
       [ 6.819838  ],
       [ 8.29931442],
       [ 8.61942638],
       [ 9.83004162],
       [10.22453454],
       [ 5.07050944],
       [ 5.67053739],
       [ 9.76487048],
       [10.22725585],
       [ 7.99190628],
       [10.38333587],
       [13.71740949],
       [ 6.65394841],
       [ 3.56505285],
       [11.31303505],
       [ 0.70609735],
       [ 6.70851986],
       [ 5

In [158]:
# отделяем независимые переменные и добавляем смещение (np.ones)
X = np.c_[np.ones((data.shape[0], 1)), data[:, 0:3]] # независимые переменные

In [170]:
# 3 и 4
lr = 0.01 # скорость обучения
iters = 1000 # кол-во шагов 
m = data.shape[0] # кол-во образцов (получается кол-во наших векторов (строк))

h = np.random.randn(4, 1) # инициализация вектора h, 4 значения h0, h1, h2, h3

# поиск
for i in range(iters):
    gradient = (2/m)*X.T @ (X @ h - Y)
    h = h - lr * gradient

print(h) # y = h0 + h1x1 + h2x2 + h3*x3 

[[ 2.10940571]
 [ 3.26834309]
 [-1.26663635]
 [ 3.90847633]]


In [168]:
# эта функция была внизу листа классной работы, эта поиск эталонного значения вектора?
h_best = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(Y)
h_best

array([[ 2.25759776],
       [ 3.2189038 ],
       [-1.3177213 ],
       [ 3.86506981]])