In [ ]:
#ЗАДАЧА 1

In [ ]:
import numpy as np

In [ ]:
a = np.array([55, -10, 14, 458, 33, -21, 5])

In [ ]:
b = np.array([89, 15, 9, 45, -22, -8, 18])

In [ ]:
c = np.array([42, -70, 38, 1742, 176, -68, -16])

In [ ]:
2 * (a + b)

array([ 288,   10,   46, 1006,   22,  -58,   46])

In [ ]:
a * c + b * (4 * c)

array([  17262,   -3500,    1900, 1111396,   -9680,    3604,   -1232])

In [ ]:
#ЗАДАЧА2

In [ ]:
#Создание массива [1. 2. 3. 4. 5. 6. 7. 8. 9.] с помощью конструктора np.linspace
mas1 = np.linspace(1, 9, 9)
print(mas1)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
#Создание массива [9. 8. 7. 6. 5. 4. 3. 2. 1.] с помощью конструктора np.linspace
mas2 = np.linspace(9, 1, 9)
print(mas2)

[9. 8. 7. 6. 5. 4. 3. 2. 1.]


In [ ]:
#Сравнение массивов между собой (операция >)
print(mas1 > mas2)

[False False False False False  True  True  True  True]


In [ ]:
#Сравнение массивов между собой (операция =)
print(mas1 == mas2)

[False False False False  True False False False False]


In [ ]:
#Сравнение массивов между собой (операция <)
print(mas1 < mas2)

[ True  True  True  True False False False False False]


In [ ]:
#Выполнить поэлементное умножение массивов
mas3 = mas1 * mas2
print(mas3)

[ 9. 16. 21. 24. 25. 24. 21. 16.  9.]


In [ ]:
#Найдите среднее значение массива полученного на шаге (print(mas1 * mas2))
mas3.mean()

18.333333333333332

In [ ]:
#Вычтите полученное среднее  (mas3.mean()), из массива (mas3 = mas1 * mas2)

In [ ]:
mas4 = mas3 - mas3.mean()
print(mas4)

[-9.33333333 -2.33333333  2.66666667  5.66666667  6.66666667  5.66666667
  2.66666667 -2.33333333 -9.33333333]


In [ ]:
#Найдите скалярное произведение массивов/векторов(mas1 и mas2)
scalar_product = np.dot(mas1, mas2)
print(scalar_product)

165.0


In [ ]:
#Преобразуйте массивы (mas1, mas2) в двумерные массивы размером 3х3
resh_mas1 = mas1.reshape(3, 3)
resh_mas2 = mas2.reshape(3, 3)
print('Массив1 равен:\n', resh_mas1)
print('Массив2 равен:\n', resh_mas2)

Массив1 равен:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Массив2 равен:
 [[9. 8. 7.]
 [6. 5. 4.]
 [3. 2. 1.]]


In [ ]:
#Примените к полученным массивам функцию dot
scalar_product_resh_mas = np.dot(resh_mas1, resh_mas2)
print(scalar_product_resh_mas)

[[ 30.  24.  18.]
 [ 84.  69.  54.]
 [138. 114.  90.]]
