ДЗ 2


In [ ]:
import numpy as np
#1. Создайте массивы 
a = np.linspace(1, 9, 9)
a

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
b = np.linspace(9, 1, 9)
b

array([9., 8., 7., 6., 5., 4., 3., 2., 1.])

In [ ]:
#2. Сравните массивы между собой
a < b

array([ True,  True,  True,  True, False, False, False, False, False])

In [ ]:
a == b

array([False, False, False, False,  True, False, False, False, False])

In [ ]:
a > b

array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
#3. Выполните поэлементное умножение массивов 
c = a * b
c

array([ 9., 16., 21., 24., 25., 24., 21., 16.,  9.])

In [ ]:
#4. Найдите среднее значение массива полученного на шаге 3
c.mean()

18.333333333333332

In [ ]:
#5. вычтите полученное среднее на шаге 4 из массива, полученного на шаге 3
c - c.mean()

array([-9.33333333, -2.33333333,  2.66666667,  5.66666667,  6.66666667,
        5.66666667,  2.66666667, -2.33333333, -9.33333333])

In [ ]:
#6. найдите скалярное произведение массивов/векторов a и b
def dot_product(a, b):
    return np.dot(a, b)

dot_product(a, b)

165.0

In [ ]:
c.sum()

165.0

In [ ]:
np.dot(a, b)

165.0

In [ ]:
#7. преобразуйте массивы a и b в двумерные массивы размером 3х3
a = a.reshape(3, 3)
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
b = b.reshape(3, 3)
b

array([[9., 8., 7.],
       [6., 5., 4.],
       [3., 2., 1.]])

In [ ]:
#8. примените к полученным на шаге 7 массивам функцию dot np.dot(a, b)
c = np.dot(a, b)
c

array([[ 30.,  24.,  18.],
       [ 84.,  69.,  54.],
       [138., 114.,  90.]])

In [ ]:
a1 = np.array([55, -10, 14, 458, 33, -21, 5])
a1

array([ 55, -10,  14, 458,  33, -21,   5])

In [ ]:
b1 = np.array([89, 15, 9, 45, -22, -8, 18])
b1

array([ 89,  15,   9,  45, -22,  -8,  18])

In [ ]:
c1 = np.array([42, -70, 38, 1742, 176, -68, -16])
c1

array([  42,  -70,   38, 1742,  176,  -68,  -16])

In [ ]:
d = 2*(a1+b1)
print(d, end='\n')

[ 288   10   46 1006   22  -58   46]


In [ ]:
d1 = np.dot(a1, c1) + np.dot(b1, 4*c1)
print(d1)

1119750


ДЗ 1

1.	Как бы вы определили машинное обучение?

Машинное обучение - это область искусственного интеллекта, которая использует алгоритмы и статистические методы для анализа данных, определения закономерностей и построения моделей, которые могут выполнять предсказания или действовать в некоторых других определенных контекстах.

2.	Можете ли вы назвать три типа задач в которых машинное обучение показывает хорошие результаты.
Машинное обучение часто применяется в следующих типах задач:

Классификация: определение категории объектов, например, определение эмоциональной окраски текста.
Регрессия: предсказание численных значений, например, предсказание цены акции.
Кластеризация: разделение объектов на группы на основе их похожести.




3.	Что такое помеченный обучающий набор? В каких моделях используются такие наборы?
Помеченный обучающий набор - это набор данных, где каждый элемент данных имеет связанный с ним метку, которая является искомым значением. Эти метки используются для того, чтобы модель машинного обучения могла изучить закономерности в данных и применить эти закономерности для предсказания значений для неизвестных данных.

Помеченные обучающие наборы используются в задачах классификации и регрессии. Например, в задаче классификации может использоваться помеченный обучающий набор, где каждый элемент данных содержит изображение объекта, а метка определяет класс, к которому он относится. В задаче регрессии помеченный обучающий набор может содержать информацию о времени и тем

4.	Какой тип алгоритма машинного обучения вы бы использовали для обучения робота прохождению неизведанной территории?
Для обучения робота прохождению неизведанной территории, возможно, был бы подходящим использовать алгоритм машинного обучения основанный на методе обучения с подкреплением (Reinforcement Learning). Этот алгоритм позволяет роботу изучать окружающую среду, получать определенные награды или штрафы в зависимости от его действий и исправлять свои действия в соответствии с полученными опытом и оценками.

5.	Какой тип алгоритма вы бы применили для разделения своих заказчиков на несколько групп.
Для разделения заказчиков на несколько групп можно использовать алгоритм кластеризации. Он основан на поиске закономерностей в данных, и позволяет группировать объекты, которые похожи друг на друга, в одну категорию. 

6.	Как вы думаете - задача фильтрации спама, это задача обучения с учителем или без учителя?
Задача фильтрации спама обычно является задачей обучения с учителем. Это означает, что у нас есть помеченные данные - сообщения, которые мы знаем, являются спамом или нет, и мы используем эту информацию для обучения модели классификации. Модель затем может использоваться для фильтрации новых, непомеченных сообщений.

7.	Назовите основные проблемы машинного обучения?
Недостаточный набор данных: недостаточный набор данных может привести к недообучению модели, что в свою очередь приведет к низкой точности предсказаний.

Переобучение: переобучение происходит, когда модель слишком подстраивается под обучающие данные, поэтому она не способна эффективно работать с новыми данными.

Неравномерное распределение классов: неравномерное распределение классов может привести к проблемам с предсказанием, поскольку модель может недооценить некоторые классы.

Несоответствие модели и задачи: использование неподходящей модели для решения определенной задачи может привести к низкой точности предсказаний.

Сложность выбора метрики: выбор неподходящей метрики для оценки

8.	Что происходит, если ваша модель хорошо работает на обучающем наборе данных и плохо обобщается на новые образцы? Предложите варианты решения проблемы.

Это называется переобучением. Когда модель хорошо работает на обучающем наборе данных, но плохо обобщается на новые данные, это говорит о том, что она запомнила и изображает слишком много характеристик обучающего набора данных, включая шум или выбросы, вместо того, чтобы выявлять основные закономерности.

Следующие варианты могут быть использованы для решения проблемы переобучения:

1/Увеличение количества данных в обучающем наборе данных.

2/Использование регуляризации для ограничения сложности модели.

3/Отбор признаков для улучшения качества модели.

4/Использование перекрестной проверки или использование валидационного набора данных для оценки качества модели.

In [ ]:
new code