In [2]:
import numpy as np

In [18]:
#Создайте массивы a = [1., 2., 3., 4., 5., 6., 7., 8., 9.]
#b = [9., 8., 7., 6., 5., 4., 3., 2., 1.] с помощью конструктора np.linspace
a = np.linspace(1, 9, 9)
b = np.linspace(9, 1, 9)
print(a)
print(b)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[9. 8. 7. 6. 5. 4. 3. 2. 1.]


In [19]:
#Сравните массивы между собой (выполните операции <, =, >)
print(a < b)
print(a == b)
print(a > b)

[ True  True  True  True False False False False False]
[False False False False  True False False False False]
[False False False False False  True  True  True  True]


In [21]:
#Выполните поэлементное умножение массивов 
c = a*b
print(c)

[ 9. 16. 21. 24. 25. 24. 21. 16.  9.]


In [23]:
#Найдите среднее значение массива полученного на шаге 3
c.mean()

18.333333333333332

In [25]:
#вычтите полученное среднее на шаге 4 из массива, полученного на шаге 3
c -=c.mean()
print(c)

[-9.33333333 -2.33333333  2.66666667  5.66666667  6.66666667  5.66666667
  2.66666667 -2.33333333 -9.33333333]


In [26]:
#    найдите скалярное произведение массивов/векторов a и b
#подсказка - скалярное произведение можно посчитать так np.dot(a,b)
scalar_multiplication = np.dot(a,b)
scalar_multiplication

165.0

In [28]:
#преобразуйте массивы a и b в двумерные массивы размером 3х3
two_dimensions_array_a = a.reshape((3,3))
two_dimensions_array_b = b.reshape((3,3))
print(two_dimensions_array_a)
print(two_dimensions_array_b)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[9. 8. 7.]
 [6. 5. 4.]
 [3. 2. 1.]]


In [30]:
#примените к полученным на шаге 7 массивам функцию dot. Как вы думаете - что вы получили в результате?
scalar_multiplication_two_dimensions_array = np.dot(two_dimensions_array_a,two_dimensions_array_b)
scalar_multiplication_two_dimensions_array

array([[ 30.,  24.,  18.],
       [ 84.,  69.,  54.],
       [138., 114.,  90.]])

матричное умножение

In [40]:
a =  np.array([55, -10, 14, 458, 33, -21, 5])
b =  np.array([89, 15, 9, 45, -22, -8, -18])
c =  np.array([42, -70, 38, 1742, 176, -68, -16])

In [46]:
#2*(a+b)
print(2*(a+b))


[ 288   10   46 1006   22  -58  -26]


In [45]:
#ac + b(4c)
print(np.dot(a, b) + np.dot(b, (4*c)))

338353
